title: Kevin Martínez-Folgar, MD, PhD.

theme: jekyll-theme-hacker

# Name of your site (displayed in the header)
name: Kevin Martínez-Folgar, MD, PhD.

# Short bio or description (displayed in the header)
description: Physician-Epidemiologist | Health Data Scientist | Health Policy | Global Health Equity 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/26907179?s=460&u=e20a764d95a0a1f20a4be6f75a21ee2c387f2169&v=4

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: kmfolgar@umich.edu
  facebook:
  flickr:
  github: thinkondata
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: kmfolgar
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/  
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: kmartinez.com


